language: go
script: GOOS=$TARGET go build -v -o craas_$TARGET
go:
  - 1.9.x
env:
  - TARGET=windows
  - TARGET=linux
  - TARGET=darwin
deploy:
  provider: releases
  api_key:
    secure: KCoTh9T9jmx93EUVZdcUtXepwQD+XciaORgza+oCvQJ5nfAPgKUz17cbXvt0A19ZYV44ANcoN8Mjm0b3z508n6JjuWDH7+7pH8IajtF5zAGaMULMDvMPXC2xnOPpwnciQXNt8FASTRn5hC13BpG68pmcUaD6qD0VWa8SoL68mXiHtk4TgEmIfrWdl4pGTFmsP37ew1Nlm1qKCOvLF4MTtjARGsGkBYkv4g/SwETtIAO6ylCcTfjhPuHYLBIMRlcGaQRf56pFt/qh2A81cc+hSXzGxVwtUMDOr5/pelPLxAiwUG9IlqCa3J1ooBfFk0f97Gd/HR1z/GgDEksdrzmKyzRVCuGnN1flnLh48aLdWpJObEs6YPY7vgXjViyliMYQauqVThY+4nAYik5QjB/3EcMMqvPMWOquvjHDj6IXD5jFt+eu9Le7ITW7RffONUf0My8tuiMb8HNmRUEcFda89Agght9D1Hb32L+AVFkP6UZw2OI9klR/ktqBXroV34IHqca2JT6hNndZpwDkWvN9msJXP6MZzN6Y9hO6ZPk3glHWAATsWwkXAGB5dHD/1p4mfCLoOlUyT4xMF/DfqFLAcDt691j0DsyxjWF4ps7iywSGw7pAkpCwmUNXV9FLkZjYsbCYZ2IIQ+KIEeaFFL0Wg1ayl3QVRW8wv+3zAj1rnQM=
  file: 
    - craas_$TARGET
  skip_cleanup: true
  on:
    repo: IQ-Inc/craas
    tags: true